spring:
    application:
        name: report-requester
        
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: validate
        open-in-view: false

    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
        producer:
            transaction-id-prefix: "tx-"
            topic: ${KAFKA_PRODUCER_TOPIC}
            sender-id: ${KAFKA_PRODUCER_SENDER_ID}
            sender-name: ${KAFKA_PRODUCER_SENDER_NAME}

server:
    port: 8081

logging:
    level:
        root: INFO

---
spring:
    config:
        activate:
            on-profile: dev

    jpa:
        show-sql: true

logging:
    level:
        org.springframework.orm.jpa: DEBUG
        org.springframework.transaction: TRACE