server:
    port: 8081
spring:
    application:
        name: report-requester
kafka:
    bootstrap-servers: localhost:9092
    producer:
        topic: reports.requests
        sender-id: report-requester
        sender-name: report-requester

