server:
    port: 8081
spring:
    application:
        name: report-requester
        
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/reports
        username: report_requester
        password: report_requester
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate.ddl-auto: validate
        properties.hibernate.temp.use_jdbc_metadata_defaults: false
        show-sql: true

kafka:
    bootstrap-servers: localhost:9092
    producer:
        topic: reports.requests
        sender-id: report-requester
        sender-name: report-requester

logging:
    level:
        root: INFO